### ISSUE TITLE
能否汉化 PuTTY CAC 项目。

### ISSUE THREAD

**Issue by wy16W2pIilK1xgqN** [bbbboom/TranslateToChinese#5]
[PuTTY CAC](https://github.com/NoMoreFood/putty-cac)  是 PuTTY 的 WIndows 增强版，
在 WIndows 平台实现 硬件密钥 的支持。
希望开发者能够汉化该项目。

o(*^＠^*)o

**Comment by bbbboom** [comment]
可以。先发一版，文本后续慢慢补。

**Comment by wy16W2pIilK1xgqN** [comment]
非常感谢你。
英盲终于有救了。
❤🌹🌹
